CREATE TABLE reservation (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(40)
);

-- INSERT INTO reservation (name) VALUES
--                                    ('Ada'),
--                                    ('Jorge'),
--                                    ('Arno'),
--                                    ('Maria'),
--                                    ('Anna');